# Site configuration for development
# See default configuration: https://jekyllrb.com/docs/configuration/default

# Plugins

plugins:
  # Need to repeat the plugins from src/_core/_config.yml here,
  # due to this override of plugins configuration.
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-mentions"
  - "jekyll-redirect-from"
  - "jemoji"
  # Only development mode
  - "jekyll-admin"
